### ISSUE TITLE
[trigger-bitrise-workflow] API token always invalid for hook

### ISSUE THREAD

**Issue by SamuelDebruyn** [bitrise-io/bitrise-steplib#1863]
I created a new Bitrise API token and used it as secret input variable for the `trigger-bitrise-workflow` step.

This is the YAML config:
```
    - trigger-bitrise-workflow:
        inputs:
        - workflow_id: ui-tests-test-launch
        - api_token: "$BITRISE_API_KEY"
```

The workflow with that ID exists.

I get  the following error:

```
Build Trigger API HTTP response status: 400 Bad Request
Build Trigger status: Invalid API token for Bitrise hook
```
