### ISSUE TITLE
restore-cache step not functioning as expected

### ISSUE THREAD

**Issue by technoplato** [bitrise-io/bitrise-steplib#4146]
pipeline url: https://app.bitrise.io/build/a8c8fe49-e8db-446f-a185-ac18a9478188

## code for restoring cache: 

```
      - restore-cache@2.2.0:
          title: "Restore iOS SDK Caches"
          inputs:
            # Use the derived SDK object ID for ios-arm64
            - key: sdk-cache-ios-arm64-${SDK_OBJECT_ID_IOS_ARM64}
      - restore-cache@2.2.0:
          title: "Restore iOS simulator SDK Caches"
          inputs:
            # Use the derived SDK object ID for ios-arm64_x86_64-simulator
            - key: sdk-cache-ios-arm64_x86_64-simulator-${SDK_OBJECT_ID_IOS_ARM64_X86_64_SIMULATOR}
```

## code for deriving cache keys

```

      - script@1:
          title: "Derive and Save SDK Cache Keys from Git LFS to Bitrise Environment"
          inputs:
            - content: |-
                #!/bin/bash

                # Array of framework paths
                FRAMEWORK_PATHS=(
                  "lib/iOS/sdk.xcframework/ios-arm64/sdk.framework/sdk"
                  "lib/iOS/sdk.xcframework/ios-arm64_x86_64-simulator/sdk.framework/sdk"
                )

                echo "Parsing Git LFS Placeholder files for Object IDs"

                # Loop through each path in the array
                for path in "${FRAMEWORK_PATHS[@]}"; do
                  echo "Checking file: $path"
                  # Check if the file exists
                  if [ -f "$path" ]; then
                    # Extract the object id using sed
                    object_id=$(sed -n 's/oid sha256:\(.*\)/\1/p' "$path")
                    echo "SED extraction: $object_id"

                    # Derive environment variable name
                    if [[ $path == *"ios-arm64/"* ]]; then
                      env_var_name="SDK_OBJECT_ID_IOS_ARM64"
                    elif [[ $path == *"ios-arm64_x86_64-simulator/"* ]]; then
                      env_var_name="SDK_OBJECT_ID_IOS_ARM64_X86_64_SIMULATOR"
                    else
                      # Skip if the pattern does not match expected values
                      echo "Unsupported path format: $path"
                      continue
                    fi

                    # Use envman to add the environment variable
                    # see https://devcenter.bitrise.io/en/builds/environment-variables.html#setting-and-managing-env-vars-during-a-build
                    envman add --key "$env_var_name" --value "$object_id"
                    echo "Set $env_var_name=$object_id"
                  else
                    echo "File not found: $path"
                  fi
                done
```

## output of cache key derivation (expected and matches what's in our build cache

```
+------------------------------------------------------------------------------+
| (3) Derive and Save SDK Cache Keys from Git LFS to Bitrise Environment       |
+------------------------------------------------------------------------------+
| id: script                                                                   |
| version: 1.2.1                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: bash                                                                |
| time: 2024-03-07T21:24:20Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
Parsing Git LFS Placeholder files for Object IDs
Checking file: lib/iOS/sdk.xcframework/ios-arm64/sdk.framework/sdk
SED extraction: 000dc392f00969d5e958afadcc49fba3c7bfa4528dfdc611e62793cc5dc87b0e
Set SDK_OBJECT_ID_IOS_ARM64=000dc392f00969d5e958afadcc49fba3c7bfa4528dfdc611e62793cc5dc87b0e
Checking file: lib/iOS/sdk.xcframework/ios-arm64_x86_64-simulator/sdk.framework/sdk
SED extraction: 54870c02481519b4d14a843adfb5c5feaa80a812b48e03ee4f14fc4de129eb6d
Set SDK_OBJECT_ID_IOS_ARM64_X86_64_SIMULATOR=54870c02481519b4d14a843adfb5c5feaa80a812b48e03ee4f14fc4de129eb6d
```

## cache functioning as expected for different piece of the workflow here: 

<img width="764" alt="image" src="https://github.com/bitrise-io/bitrise-steplib/assets/6922904/596468bb-7951-4a02-90fe-6308c117bc94">

## showing the cache has the expected artifacts

<img width="1920" alt="image" src="https://github.com/bitrise-io/bitrise-steplib/assets/6922904/c68d9a3e-7e6e-4abf-a3e7-136f56413772">
